source 'https://github.com/CocoaPods/Specs.git'

target 'ApsaraAOP', :exclusive => true do
  pod "ApsaraAOP", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ApsaraAOP", :path => "../"
  pod 'OCMockito', '~> 1.0'
end
